enable 6 document types of sync-job to be called from management api
thoth-station/management-api pull request #884
Opened 2022-04-22 23:06 UTC by Gregory-Pereira

## Related Issues and Dependencies

Partially addresses: https://github.com/thoth-station/thoth-application/issues/2513 (task 3 / 4)

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

New post endpoints for `/graph/sync-job/{component-name}`, that will trigger the sync job for those documents.
Component names:
1. adviser
2. solver
3. revsolver
4. package-extract
5. provenance-checker
6. security-indicators

/cc @harshad16 @fridex

2022-04-22 23:06 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **fridex** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @fridex` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fmanagement-api).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/management-api/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fridex"]} -->

2022-04-22 23:09 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | aca2c62bc7cc20b0c2d5ca99b1dc949c10459651 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_management-api/884/pre-commit/1517641064389808128) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=management-api&pr=884). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/management-api/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-04-25 16:35 UTC, fridex commented on openapi/openapi.yaml
> +  /graph/sync-job/solver:
Maybe could be parametrized with an enum?

```suggestion
  /graph/sync-job/{type}:
```

2022-04-25 16:35 UTC, fridex commented on thoth/management_api/api_v1.py
> +            force=force, graph=GRAPH, graceful=graceful, is_local=False
The HTTP server that we run has multiple workers that try to serve requests. Each worker has a timeout for requests to be served. If the worker is not able to deliver any response, it is killed. Considering we will sync thousands of documents, this job needs to be done asynchronously as a job in the cluster.

We have routies in thoth-common that can submit jobs to the cluster using the OpenShift abstraction. In that case, the sync will happen in the cluster asynchronously to the request and will not timeout.

2022-05-09 16:01 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | ba3869792375b94d3015ff9ba4a2c4e92e02aa62 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_management-api/884/pre-commit/1523693937896722432) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=management-api&pr=884). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/management-api/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-05-09 17:29 UTC, harshad16 requested changes
Great effort :tada: 

Is this been tested ? 
does the change of the open API version cause any issue with the existing schema ?

2022-05-09 17:29 UTC, harshad16 commented on thoth/management_api/sync_job_types.py
> +class document_type(Enum):
can we move this under the function `schedule_sync_job`?
i don't see use of this anywhere else apart from schedule_sync_job

2022-05-09 17:29 UTC, harshad16 commented on openapi/openapi.yaml
> +        - name: document_type
can we do the enums with some description of the enum options and 
schema with enums ?

```
description: type of documents ...
Advise: ...
solver:..
..
schema:
  type: string
  enum: [advise,solver,etc]
```

2022-05-10 17:51 UTC, Gregory-Pereira commented on openapi/openapi.yaml
> +        - name: document_type
Not certain about what type of descriptions we would have for the enum options, its simply that we would be syncing those types of documents. Let me know if this does not work.

2022-05-10 18:02 UTC, harshad16 commented on openapi/openapi.yaml
> +        - name: document_type
Here is the documents: https://swagger.io/docs/specification/data-models/enums/

2022-06-06 20:26 UTC, harshad16 requested changes
thanks for all the changes
some more suggestions.

2022-06-06 20:26 UTC, harshad16 commented on openapi/openapi.yaml
> +  /graph/sync-job/{docuement_type}:
```suggestion
  /graph/sync-job:
```
I think this is not needed anymore.

2022-06-06 20:26 UTC, harshad16 commented on thoth/management_api/api_v1.py
> +        security_indicators = 5
why is this required.
seems like sync_job take the value as string
https://github.com/thoth-station/sync-job/blob/9efe989935f77df47cd2e9ee4efee21c0bfa088a/app.py#L46
https://github.com/thoth-station/storages/blob/7d01189226ebac008f8cb13553dd72b186ff31c0/thoth/storages/sync.py#L557

2022-06-06 20:26 UTC, harshad16 commented on thoth/management_api/api_v1.py
> +        document_type=SyncJobDocumentType(document_type),
```suggestion
        document_type=document_type,
```

2022-06-06 20:26 UTC, harshad16 commented on openapi/openapi.yaml
> +openapi: "3.1.2"
```suggestion
openapi: "3.0.0"
```
enum is available in openapi 3.0, so let's keep that.

2022-06-07 18:19 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | 4cf827542357a535fabf639823338e9d894f4e63 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_management-api/884/pre-commit/1534237216337825792) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=management-api&pr=884). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/management-api/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-06-07 19:12 UTC, harshad16 requested changes
some more changes required

2022-06-08 17:32 UTC, sesheta commented
@Gregory-Pereira: The following test **failed**, say `/retest` to rerun all failed tests or `/retest-required` to rerun all mandatory failed tests:

Test name | Commit | Details | Required | Rerun command
--- | --- | --- | --- | ---
aicoe-ci/prow/pre-commit | c7daa00a18b8f66a91e7a2a612dc7ec861ffe398 | [link](https://prow.operate-first.cloud/view/s3/ci-prow/prow-logs/pr-logs/pull/thoth-station_management-api/884/pre-commit/1534588415327080448) | true | `/test pre-commit`

[Full PR test history](https://prow.operate-first.cloud/pr-history?org=thoth-station&repo=management-api&pr=884). [Your PR dashboard](https://prow.operate-first.cloud/pr?query=is%3Apr%20state%3Aopen%20author%3AGregory-Pereira). Please help us and [open an issue](https://github.com/thoth-station/management-api/issues?q=is:issue+is:open) when you hit one in your PR.

<details>

Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository. I understand the commands that are listed [here](https://go.k8s.io/bot-commands).
</details>
<!-- test report -->

2022-06-08 17:44 UTC, harshad16 approved these changes
/lgtm
thanks :100:

2022-06-08 17:45 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/thoth-station/management-api/pull/884#pullrequestreview-1000186187" title="LGTM">harshad16</a>*
To complete the [pull request process](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process), please assign **fridex** after the PR has been reviewed.
You can assign the PR to them by writing `/assign @fridex` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=thoth-station%2Fmanagement-api).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/thoth-station/management-api/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":["fridex"]} -->

2022-06-10 15:27 UTC, merged